apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "robotshop.fullname" . }}-be
  namespace: robotshop
  labels:
    {{- include "robotshop.labels" . | nindent 4 }}
    app.kubernetes.io/component: be
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "robotshop.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: be
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "robotshop.labels" . | nindent 8 }}
        app.kubernetes.io/component: be
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "robotshop.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-be
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.be_image.repository }}:{{ .Values.be_image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.be_image.pullPolicy }}
          env:
            - name: MONGO_URL
              value: {{ .Values.be_env.mongoUrl | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.be_service.port }}
              protocol: TCP
          {{- with .Values.be_probe.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.be_probe.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
