apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: require-labels-on-namespace
  namespace: robotshop
spec:
  validationFailureAction: Enforce
  rules:
  - name: check-app-label
    match:
      any:
      - resources:
          kinds:
          - Deployment
    validate:
      message: "The namespace robotshop must have a label named owner"
      pattern:
        metadata:
          labels:
            app: "?*"
            